# -*- coding: utf-8 -*-
"""ibm_watson_tts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YFgEklGT_o-u0nwleedfAW5cirorTPwC
"""

pip install --upgrade "ibm-watson>=4.4.0"

from ibm_watson import TextToSpeechV1
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
from google.colab import files
#enter your API KEY
APIkey = 'NQiooQf1LF88BkCSO87ocBT0Wg3xFI2kTDHgtmpNEwN8'
#example for Dallas server 
TTSurl = 'https://api.au-syd.text-to-speech.watson.cloud.ibm.com'
inputTXT = "hello this is my result"

authenticator = IAMAuthenticator(APIkey)
text_to_speech = TextToSpeechV1(
    authenticator=authenticator
)

text_to_speech.set_service_url(TTSurl)

with open('result.mp3','wb') as audio_file:
    audio_file.write(text_to_speech.synthesize(inputTXT, voice='en-AU_MadisonVoice', accept = 'audio/mp3').get_result().content)
    files.download('result.mp3')